### ISSUE TITLE
[tea]: qwer

### ISSUE THREAD

**Issue by testtip** [testtip/bounties#16]
**Repository**: **[tea-spoon/tea](http://github.chaintip.org/tea-spoon/tea)**
**Issue [#17](http://github.chaintip.org/tea-spoon/tea/issues/17)**: **qwer**

qwerqwer

***
**Total Bounty**: `0.00029214 BCH`| `~   0.40 USD`

To claim this bounty, get a pull request merged with ```@testtip fixes #17``` in the creation comment.

**On-Chain Tips**:
- `0.00014607 BCH`| `~   0.20 USD` [from](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld40d25e5zyshraq5xygr305yday4y0gqgaehs) **tea-spoon** to return to sender in 3 days from now.
- `0.00014607 BCH`| `~   0.20 USD` [from](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4tsjdtrrx522fammehmj4gtwgvavqwjfw8ym) **block-spider** to return to sender in 1 day from now.

***
**Pull Requests Fixing Issue**:
- [PR [#18](http://github.chaintip.org/tea-spoon/tea/pull/18) - fixed issue] Create ewer
- [PR [#20](http://github.chaintip.org/tea-spoon/tea/pull/20)] Create arty
- [PR [#21](http://github.chaintip.org/tea-spoon/tea/pull/21)] Create arty

**Comment by tea-spoon** [comment]
@testtip

**Comment by testtip** [comment]
You can't tip a bounties issue... it creates all sorts of confusion :)

**Comment by tea-spoon** [comment]
@block-spider @testtip

**Comment by testtip** [comment]
@block-spider, you've [been sent](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4jgyjq4jrtsz2suvnqt27ulplqpc6lln72mw) `0.00014677 BCH`| `~   0.20 USD` by @tea-spoon via [chaintip](http://www.chaintip.org).
